# Generated by Django 5.2.7 on 2025-10-25 01:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Baraja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('visibilidad', models.CharField(choices=[('privada', 'Privada'), ('enlace', 'Por Enlace'), ('publica', 'Pública')], default='privada', max_length=10)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barajas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Baraja',
                'verbose_name_plural': 'Barajas',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('duracion_minutos', models.IntegerField(default=0)),
                ('tarjetas_estudiadas', models.IntegerField(default=0)),
                ('baraja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='core.baraja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión',
                'verbose_name_plural': 'Sesiones',
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('anverso_reverso', 'Anverso/Reverso'), ('cloze', 'Cloze (Relleno de huecos)'), ('imagen_oculta', 'Imagen Oculta'), ('audio', 'Audio'), ('pareo', 'Pareo')], default='anverso_reverso', max_length=20)),
                ('anverso', models.TextField()),
                ('reverso', models.TextField()),
                ('extra', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='tarjetas/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audios/')),
                ('etiquetas', models.CharField(blank=True, help_text='Separadas por comas', max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('baraja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='core.baraja')),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
            },
        ),
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ease_factor', models.FloatField(default=2.5)),
                ('intervalo', models.IntegerField(default=1)),
                ('repeticiones', models.IntegerField(default=0)),
                ('proximo_estudio', models.DateField(default=django.utils.timezone.now)),
                ('tarjeta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='programacion', to='core.tarjeta')),
            ],
            options={
                'verbose_name': 'Programación',
                'verbose_name_plural': 'Programaciones',
            },
        ),
    ]
