# Generated by Django 5.2.7 on 2025-10-25 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('codigo_invitacion', models.CharField(blank=True, max_length=10, unique=True)),
                ('alumnos', models.ManyToManyField(blank=True, related_name='clases_alumno', to=settings.AUTH_USER_MODEL)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_docente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
            },
        ),
        migrations.CreateModel(
            name='HistorialRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(choices=[(1, 'Otra vez'), (2, 'Difícil'), (3, 'Bien'), (4, 'Fácil')])),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('tiempo_respuesta_segundos', models.IntegerField(default=0)),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='core.tarjeta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Respuesta',
                'verbose_name_plural': 'Historial de Respuestas',
                'ordering': ['-fecha_respuesta'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('estudiante', 'Estudiante'), ('docente', 'Docente/Coach'), ('colaborador', 'Colaborador/Editor'), ('administrador', 'Administrador')], default='estudiante', max_length=20)),
                ('idioma', models.CharField(default='es', max_length=10)),
                ('modo_oscuro', models.BooleanField(default=False)),
                ('racha_dias', models.IntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_limite', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('baraja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='core.baraja')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='core.clase')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
            },
        ),
    ]
